#!/bin/bash
set -e

repl () {
  GRENCH_PORT=7800 grench main trident.cli.util/-main "$PWD" trident.build/-main "$@"
}

dev () {
  cd target/$1
  shift
  clj -Adev "$@" -e "(init)" -r
}

deploy () {
  repl mono reset
  repl -w repl:util:jwt:rum:staticweb:cljs-http:cli:build:ring:firebase:firestore:views:ion:ion-dev:datascript:datomic:datomic-cloud:web:frontend:docs deploy
}

"$@"
